// Generated by https://quicktype.io

export interface Projecto {
    code:    string;
    data:    Datum[];
    message: string;
    status:  string;
}

export interface Datum {
    artistaId:    number;
    canciones:    Canciones[];
    descripcion:  string;
    discografica: string;
    duracion:     number;
    fecha:        string;
    fotoPortada:  string;
    genero:       string;
    id:           number;
    lanzamiento:  string;
    nombre:       string;
    numCanciones: number;
    tipo:         string;
}

export interface Canciones {
    duracion: number;
    nombre:   string;
    track:    number;
}
