// Generated by https://quicktype.io

export interface Artista {
    code:    string;
    data:    Data;
    message: string;
    status:  string;
}

export interface Data {
    administradores:     Administradores[];
    biografia:           string;
    departamento:        string;
    fotoPerfil:          string;
    fotoPortada:         string;
    genero:              string;
    id:                  number;
    nombre:              string;
    proyectos:           Proyectos[];
    seguidores:          Seguidores[];
    totalReproducciones: number;
    totalSeguidores:     number;
}

export interface Administradores {
    fechaRegistro: string;
    nivel:         string;
    usuarioNombre: string;
}

export interface Proyectos {
    fecha:       string;
    id:          number;
    lanzamiento: string;
    nombre:      string;
}

export interface Seguidores {
    fecha:        string;
    usuarioApodo: string;
}
